---

- name: Adds Midonet's repository
  apt_repository: repo='deb http://repo.midonet.org/midonet/v2015.01 stable main' state=present
  tags: Midonet

- name: Adds Midonet's Openstack repository
  apt_repository: repo='deb http://repo.midonet.org/openstack-juno stable main' state=present
  tags: Midonet

- name: Adds Midonet's 3rd Party Tools repository
  apt_repository: repo='deb http://repo.midonet.org/misc stable main' state=present
  tags: Midonet

- name: Adds the key for Midonet's repository
  apt_key: url=http://repo.midonet.org/packages.midokura.key state=present
  tags: Midonet

- name: Add Ubuntu Cloud Archivo rep
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main' state=present
  tags: common-utils

- name: Update system dist files
  action: apt update_cache=yes
  tags: common-utils

- name: Install several packages needed and utilities
  action: apt pkg={{ item }} state=installed
  tags: common-utils
  with_items:
    - ubuntu-cloud-keyring
    - htop
    - vim
    - python-pip
    - curl
    - git
    - unzip
    - python-software-properties

